services:
  api:
    build: .
    image: weather-service:dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./:/app
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  test:
    build: .
    image: weather-service:dev
    environment:
      - PYTHONPATH=/app
      - OPENWEATHER_API_KEY=test-key
    volumes:
      - ./:/app
    command: pytest

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: weather-frontend:dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - api
